version: '3'

services:
    sync-tools:
        container_name: sync-tools
        image: plex-emby-sync-tools:test
        ports:
            - 8080:80
        volumes:
            - ./config:/config
            - ./src:/src # Only needed if you want to edit the code
        restart: unless-stopped
    mongodb:
        container_name: mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: dragon
        volumes:
            - ./config/data/db:/data/db
        ports:
            - "27017:27017"
    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: dragon
            ME_CONFIG_MONGODB_URL: mongodb://root:dragon@mongodb:27017/
        ports:
            - "8081:8081"
        depends_on:
            - mongodb

