version: '3'

services:
    frontend:
            build:
                context: ./front-end
                dockerfile: Dockerfile
            ports:
                - "8080:80"
            restart: unless-stopped
    backend:
            build:
                context: ./
                dockerfile: Dockerfile  # Specify the Dockerfile for your Python FastAPI backend
            ports:
                - "8000:8000"  # Adjust the port as needed for your FastAPI app
            volumes:
                - ./config:/config
                - ./src:/src # Only needed if you want to edit the code
            restart: unless-stopped
    mongodb:
        container_name: mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: dragon
        volumes:
            - ./config/data/db:/data/db
        ports:
            - "27017:27017"
        restart: unless-stopped
    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: dragon
            ME_CONFIG_MONGODB_URL: mongodb://root:dragon@mongodb:27017/
        ports:
            - "8081:8081"
        depends_on:
            - mongodb
        restart: unless-stopped
